apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentrikat.fullname" . }}-secret
  labels:
    {{- include "sentrikat.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  DATABASE_URL: {{ include "sentrikat.databaseUrl" . | quote }}
